name: Default
on:
  push:
    branches: [ Edu-demo ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .

    - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
      with:
        java-version: '8'

    - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
      env:
        VID: ${{ secrets.VERACODE_API_ID }} # Lembrar de criar as credenciais no Secrets
        VKEY: ${{ secrets.VERACODE_API_KEY}}
        AppName: Github Actions - ${{ github.repository }}
      with:
        vid: '$VID'
        vkey: '$VKEY'
        criticality: 'VeryHigh'
        appname: '$AppName'
        createprofile: true
        filepath: 'veracode.zip'
        deleteIncompleteScan: false
        version: ${{ github.run_id }}

    - name: Veracode SCA
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }} # Lembrar de criar as credenciais no Secrets
      run: |
        curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s scan --update-advisor

    - name: build
      run: npm build
    
    - name: Veracode Pipeline Scan
      env:
        VID: ${{ secrets.VERACODE_API_ID }} # Lembrar de criar as credenciais no Secrets
        VKEY: ${{ secrets.VERACODE_API_KEY}}
        CaminhoArquivo: 'veracode.zip'
      run: |
        curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        java -jar pipeline-scan.jar -vid $VID -vkey $VKEY -f $CaminhoArquivo --issue_details true
